#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs momor onto your system into ~/.local, making it available as ~/.local/bin/momor.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export MOMOR_CHANNEL=$(<crates/momor/RELEASE_CHANNEL)
export MOMOR_UPDATE_EXPLANATION="You need to fetch and rebuild momor in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="momor-linux-${arch}.tar.gz"
export MOMOR_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
